basePath: /
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This api is an approach of clean architecture using golang made by
    Jonathan Malagueta
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Golang clean architecture example
  version: "1.0"
paths: {}
swagger: "2.0"
